version: '3.8'

services:
  app:
    image: yohanesokta/serbailmu_api:latest
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_PORT : ${APP_PORT}
      APP_DEBUG : ${APP_DEBUG}
      APP_KEY: ${APP_KEY}
      DB_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public"
       
      NODE_ENV: ${NODE_ENV}
      GOOGLE_CLIENT_SECRET : ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CLIENT_ID : ${GOOGLE_CLIENT_ID}

      ID_MERCHEN : ${ID_MERCHEN}
      CLIENT_KEY : ${CLIENT_KEY}
      SERVER_KEY : ${SERVER_KEY}
      SERVER_URL : ${SERVER_URL}
    command: sh -c "npx prisma migrate deploy && node dist/api/index.js"

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: